name: inichain

services:
  node:
    image: ghcr.io/lushdog/inichain:latest
    restart: unless-stopped
    cpuset: '${CPU_SET}'
    environment:
      - ETH_ADRRDESS=${ETH_ADRRDESS}
      - WORK_NAME=${WORK_NAME}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
