name: inichain

services:
  node:
    image: ghcr.io/lushdog/inichain:latest
    restart: unless-stopped
    cpuset: '${CPU_SET}'
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
    environment:
      - ETH_ADRRDESS=${ETH_ADRRDESS}
      - WORK_NAME=${WORK_NAME}
      - POOL=${POOL}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
